/**
 * @author		Paweł Woźniak
 * @created		2021-08-12
 * @description	Put here all constants that will be referenced in apex code.
 *              If all references in APEX code will use constants then changes in picklist will require changes only here.
 *              For picklists you need to provide API name not label.
 */

public with sharing class Constants {
	// Naming: OBJECTNAME_FIELDNAME_VALUE

	/********************* Account (Account) *********************/
	// Type (Type)
	public final static String ACCOUNT_TYPE_PARTNER = 'Partner';
}